// <auto-generated />
using KonyvtarNo2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KonyvtarNo2.Migrations
{
    [DbContext(typeof(KonyvtarNo2Context))]
    partial class KonyvtarNo2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("KonyvtarNo2Library.Models.Kolcsonzes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Cim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Iro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KolcsonzoId")
                        .HasColumnType("int");

                    b.Property<string>("Mufaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KolcsonzoId");

                    b.ToTable("Kolcsonzes");
                });

            modelBuilder.Entity("KonyvtarNo2Library.Models.Kolcsonzo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SzulIdo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kolcsonzo");
                });

            modelBuilder.Entity("KonyvtarNo2Library.Models.Kolcsonzes", b =>
                {
                    b.HasOne("KonyvtarNo2Library.Models.Kolcsonzo", null)
                        .WithMany("Kolcsonzes")
                        .HasForeignKey("KolcsonzoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KonyvtarNo2Library.Models.Kolcsonzo", b =>
                {
                    b.Navigation("Kolcsonzes");
                });
#pragma warning restore 612, 618
        }
    }
}
